FROM node:latest

LABEL description="Client side React app for the BestCRM Demo Application. This application is used to demonstrate Sisense."


WORKDIR /app
ARG NPM_TOKEN  
COPY .npmrc .npmrc
COPY ["package.json", "package-lock.json", "./"]

RUN npm install
RUN rm -f ./client/.npmrc

COPY . .

# SteveL: added patch=package to fix sisensejs-infuse-react
COPY patches .
# End of fix.

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]