name: Deploy Backend
on:
    workflow_dispatch:
        inputs:
            branch_ref:
                description: Deploy using branch
                default: main
                required: true
            deploy_env:
                description: 'Environment'
                required: true
                default: 'trial-dev'
                type: choice
                options:
                    - trial-dev
                    - trial-prod
env:
    DEPLOY_ENV: ${{ inputs.deploy_env }}
    AWS_LIGHTSAIL_SERVICE_NAME: trial-magpie-backend

jobs:
    deploy:
        name: Build and deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ inputs.branch_ref }}
            - name: Install Utilities
              run: |
                  sudo apt-get update
                  sudo apt-get install -y jq unzip
            - name: Install AWS Client
              run: |
                  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                  unzip awscliv2.zip
                  sudo ./aws/install || true
                  aws --version
                  curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
                  sudo mv "lightsailctl" "/usr/local/bin/lightsailctl"
                  sudo chmod +x /usr/local/bin/lightsailctl
            - name: Set AWS Region based on DEPLOY_ENV
              run: |
                  case ${{ inputs.deploy_env }} in
                    trial-dev) echo "AWS_REGION=ca-central-1" >> $GITHUB_ENV ;;
                    trial-prod) echo "AWS_REGION=us-east-2" >> $GITHUB_ENV ;;
                  esac
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-region: ${{ env.AWS_REGION }}
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            - name: Build Docker Image
              run: docker build -f Dockerfile -t ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }}:release .
              working-directory: ./backend
            - name: Push and Deploy
              run: |
                  service_name=${{ env.AWS_LIGHTSAIL_SERVICE_NAME }}
                  aws lightsail push-container-image \
                    --region ${{ env.AWS_REGION }} \
                    --service-name ${service_name} \
                    --label ${service_name} \
                    --image ${service_name}:release
                  aws lightsail get-container-images --service-name ${service_name} | jq --raw-output ".containerImages[0].image" > image.txt
                  jq --arg image $(cat image.txt) '.containers.trialmagpiebackend.image = $image' ./backend/container.template.json > container.json
                  cat container.json
                  aws lightsail create-container-service-deployment --service-name ${service_name} --cli-input-json file://$(pwd)/container.json
